title: TC1001S Herramientas computacionales: el arte de la programación
logo: Loguito.png
description: Maribel Coronado  A01197537          Meli 1929393
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
