title: "TC1001S.3"
logo: Loguito.png
description: "Herramientas computacionales: el arte de la programacion" | Maribel Coronado Flores A01197537 | Melissa Aldana Almanza A00827343 | José Manuel López Delgado A00571541 | Luis Pompeyo Rodríguez Guajardo A01570428 | Victor Aguilar A00828964
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
