theme: jekyll-theme-minimal
title: Herramientas computacionales: el arte de la programación
logo: https://lh3.googleusercontent.com/8DcAmLvQgEL53ozToFDryJQYP5dfN7WnQuTJzmiwptRsFpCIDyzHQeBUzvsmBUXvcdJyjm4=s85
description: TC1001S
show_downloads: true
google_analytics:
